export const PageLocators = {
    zipLogoText: '//h1[@class="sviee9k"]',
    emailField: '//input[@id="email"]',
    emailNextButton: '//div//button[@class="bp730pe s1hfe04e sienn4l sslpsxn beysths ciu5cso l16phmm6"]/span',
    forgotTextPW: '//a[@data-test="z-link"]',
    passwordField: '//input[@id="password"]',
    loginButton: '//button[@data-testid="loginButton"]',
    challangeHeader: '//div[@class="t11vrf9q w171sleo suktnmo l9x6fqg cyr962 t1t13vor t1ft2z5b"]',
    statusDropDownBudget: '//span[contains(text(), "Budget Approval")]/../../../div[@class= "MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary  css-190lo7w"]',
    statusDropDownLegal: '//span[contains(text(), "Legal Approval")]/../../../div[@class= "MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary  css-190lo7w"]',
    statusDropDownDepartment: '//span[contains(text(), "Department Approval")]/../../../div[@class= "MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary  css-190lo7w"]',
    statusDropDownManager: '//span[contains(text(), "Manager Approval")]/../../../div[@class= "MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary  css-190lo7w"]',
    labelManagerApproval: '//span[@class="t11vrf9q w171sleo s1hfe04e sienn4l cyr962 llybbtt" and contains(text(), "Manager Approval")]',
    labelLegalApproval: '//div[@class="nprkfc9"]//span[contains(text(), "Legal Approval")]',
    labelBudgetApproval: '//span[@class="t11vrf9q w171sleo s1hfe04e sienn4l cyr962 llybbtt" and contains(text(), "Budget Approval")]',
    buttonLegalApproval: '//div[@class="nprkfc9"]//span[contains(text(), "Legal Approval")]/../../..//button[@id="node-diagram-approval-button"]',
    buttonManagerApproval: '//div[@class="nprkfc9"]//span[contains(text(), "Manager Approval")]/../../..//button[@id="node-diagram-approval-button"]',
    buttonBudgetApproval: '//div[@class="nprkfc9"]//span[contains(text(), "Budget Approval")]/../../..//button[@id="node-diagram-approval-button"]',
    checkLegalApprovalVerified: '//div[@class="t11vrf9q w171sleo suktnmo l9x6fqg cyr962" and contains(text(), "Legal Approval")]/../..//div[contains(text(), "Approved")]',
    checkBudgetApprovalVerified: '//div[@class="t11vrf9q w171sleo suktnmo l9x6fqg cyr962" and contains(text(), "Budget Approval")]/../..//div[contains(text(), "Approved")]',
    checkManagerApprovalVerified: '//div[@class="t11vrf9q w171sleo suktnmo l9x6fqg cyr962" and contains(text(), "Manager Approval")]/../..//div[contains(text(), "Approved")]',
    clickApprove: '//button[@id="rdp-node-popover-approve-button"]/span[@class="e18p30ex"]',
    clickXmark: '//button[@class="clickable-reset w1nrnyah f13priqs infkgbp"]',
    statusSetInProgress: '//div[contains(text(), "In progress:)]',
    statusCheckInProgress: '//span[contains(text(), "Manager Approval")]/../../../div//div[contains(text(), "In progress")]',
    UpdaedPriceHoover: '//div[contains(text(), "Updated price")]/../../div[@class="cmhls1"]',
    updatedPriceClickPen: '//div[contains(text(), "Updated price")]/../../div[@id="editable-state"]//button[@class="clickable-reset e3fs9l5 f13priqs infkgbp"]',
    inputUpdatedPrice: '//label[contains(text(), "Updated price")]/..//div/input',
    clickSaveButton: 'span:has-text("Save")',
    clickSaveChanges: 'span:has-text("Save changes")',
    //div[@class="cd8pwiq cmpi8br"]/div/div[@class="f2qjx8s g1nt79xs"]/button/span[contains(text(), "Save")]
    updatePriceChangeHeader: 'h3.t11vrf9q.w1g6n6hq.s7avxrs.t1sk5cdy.cyr962.e18p30ex.w1oidi01',
    updatedPriceCheck: '//div[contains(text(), "Updated price")]/../../div/div/div[@class="t11vrf9q w1g6n6hq s1hfe04e sienn4l cyr962"]',
};